FROM php:8.2-fpm-alpine

WORKDIR /var/www/html

RUN apk add --no-cache nginx git curl zip unzip oniguruma-dev libxml2-dev \
    && docker-php-ext-install pdo_mysql mbstring bcmath

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

RUN chmod -R 775 storage bootstrap/cache

COPY docker/nginx.production.conf /etc/nginx/http.d/default.conf

RUN echo '[www]' > /usr/local/etc/php-fpm.d/www.conf \
    && echo 'listen = /var/run/php-fpm.sock' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'listen.owner = nginx' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'listen.group = nginx' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'listen.mode = 0660' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'user = nginx' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'group = nginx' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm = dynamic' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.max_children = 5' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.start_servers = 2' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.min_spare_servers = 1' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.max_spare_servers = 3' >> /usr/local/etc/php-fpm.d/www.conf

EXPOSE 10000

CMD sh -c "php-fpm -D -y /usr/local/etc/php-fpm.d/www.conf && sleep 1 && nginx -g 'daemon off;'"